In [ ]:
import torch

In [ ]:
# tensor
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# Check the number of dimensions of vector
print('ndim', vector.ndim)

# shape
print('vector', vector.shape)

ndim 1
vector torch.Size([2])


In [ ]:
# create a matrix
matrix = torch.tensor([[7, 7],
                      [8,8]])

matrix

tensor([[7, 7],
        [8, 8]])

In [ ]:
print('ndim', matrix.ndim)
print('shape', matrix.shape)

ndim 2
shape torch.Size([2, 2])


<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png" alt="Deskripsi Gambar" width="300" height="200">


In [ ]:
# random tensor

random_tensor = torch.rand(size=(3, 4)) # 3 X 4
random_tensor, random_tensor.dtype

(tensor([[0.3307, 0.6790, 0.6878, 0.5332],
         [0.9260, 0.7610, 0.0358, 0.9918],
         [0.3661, 0.7605, 0.1759, 0.7852]]),
 torch.float32)

In [ ]:
random_tensor = torch.zeros(size=(3, 4)) # 3 X 4
random_tensor, random_tensor.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
random_tensor = torch.ones(size=(3, 4)) # 3 X 4
random_tensor, random_tensor.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
# range
zero_to_five = torch.range(start= 0, end = 5, step = 1)
zero_to_five

<ipython-input-10-660cbe0856a3>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_five = torch.range(start= 0, end = 5, step = 1)


tensor([0., 1., 2., 3., 4., 5.])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # default float 32
                               device = None, # default using cpu
                               requires_grad=False # if True, operations performed on the tensor are recorded
                               )
float_32_tensor.dtype, float_32_tensor.device, float_32_tensor.requires_grad

(torch.float32, device(type='cpu'), False)

In [ ]:
# manipulation tensor
tensor = torch.tensor([7, 3])
tensor = tensor + 10
tensor = torch.multiply(tensor , 10)

tensor

tensor([170, 130])

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [ ]:
tensor*tensor # multiply with it self

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor) # sum all tensor

tensor(14)

In [ ]:
# matrix
tensor_A = torch.tensor([[1, 2],
                         [2, 3],
                         [3, 4]], dtype = torch.float32)

tensor_B = torch.tensor([[4, 3],
                         [2, 3],
                         [3, 4]], dtype = torch.float32)

torch.matmul(tensor_A, tensor_B) # is not correct

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# how we transpose one of tensor

print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])
tensor([[4., 2., 3.],
        [3., 3., 4.]])


In [ ]:
# mm is short matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[10.,  8., 11.],
        [17., 13., 18.],
        [24., 18., 25.]])

y
=
x
⋅
A
T
+
b

data Sample  :

```python
random_tensor =
[[0.8331, 0.2715, 0.0583, 0.7611],
 [0.5846, 0.0061, 0.4948, 0.1087],
 [0.4553, 0.6904, 0.9140, 0.1416]]
```
- weight from input hidden layer:

  W_hidden = [[0.1, 0.2], [0.3, 0.4], [0.5, 0.6], [0.7, 0.8]]
- Bias of hidden layer:

  b_hidden = [0.1, 0.2]
- weight of hidden layer to output :
  
  W_output = [0.4, 0.5]
- Bias of layer output:
  
  b_output = 0.3

Forward Propagation:
Input in to hidden layer:
 - hidden_input = input.dot(W_hidden) + b_hidden
 - hidden_input =
  
```[[0.8331, 0.2715, 0.0583, 0.7611],
      [0.5846, 0.0061, 0.4948, 0.1087],
      [0.4553, 0.6904, 0.9140, 0.1416]]
      dot
      [[0.1, 0.2],
      [0.3, 0.4],
      [0.5, 0.6],
      [0.7, 0.8]] +
      [0.1, 0.2]
```

In [ ]:
# feedforward layer
torch.manual_seed(24)

linear = torch.nn.Linear(in_features=2,
                         out_features=6)

x = tensor_A
linear(x)

tensor([[-0.5555, -0.7159,  0.7139,  0.7242,  0.0055, -0.3667],
        [-0.3582, -1.2733,  1.0576,  1.0469, -0.3629, -0.4832],
        [-0.1610, -1.8307,  1.4013,  1.3697, -0.7314, -0.5997]],
       grad_fn=<AddmmBackward0>)

In [ ]:
# aggregation
x = torch.arange(start = 0, end = 10, step = 2)
print('min', min(x))
print('max', max(x))
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype

min tensor(0)
max tensor(8)
Mean: 4.0


In [ ]:
# positional
tensor = torch.arange(0, 10, 1)

print('min', tensor.argmax())
print('max', tensor.argmin())

min tensor(9)
max tensor(0)


In [ ]:
# change dtype
tensor.type(torch.int8)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8)

In [ ]:
# squeeze and unsqueze
torch.unsqueeze(tensor, dim = 1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
torch.squeeze(tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# stack
x = torch.arange(0, 8)

x_stacked = torch.stack([x, x], dim = 0)

x_stacked

tensor([[0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7]])

In [ ]:
# indexing

x = torch.arange(1, 10).reshape(1, 3, 3) # reshape matrix
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# indexing bracket

x[0][1]

tensor([4, 5, 6])

In [ ]:
# indexing

print('0 to 1 ', x[:, :, 1])
print('1 to 1 ', x[:, 1, 1])

0 to 1  tensor([[2, 5, 8]])
0 to 1  tensor([5])


In [ ]:
# change array to tensor
import numpy as np
array = np.arange(1, 10, 1)
tensor = torch.from_numpy(array)

array, tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# learn about GPU
!nvidia-smi

Mon Apr 29 06:59:53 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# run pytorch in GPU
torch.cuda.is_available()

True

In [ ]:
# swicth cuda
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'